nginx:
  image: mahata/gwiki-nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - gwiki
  restart: always

gwiki:
  build: .
  expose:
    - "8080"
  ports:
    - "8080:8080"
  environment:
    GOPATH: /root/go-workspace
  working_dir: /root/go-workspace/src/github.com/mahata/gwiki
  command: go run main.go -nginx
  volumes:
    - /usr/local/gwiki/data:/usr/local/gwiki/data
  restart: always
